/**
 * Simplified Question Creation Action for Learning
 * 
 * This is a simplified version of createQuestionsAndAssignForReview.js
 * designed for learning purposes with extensive logging and comments.
 * 
 * What this script does:
 * 1. Reads AI-generated questions from response.md
 * 2. Parses the JSON array of questions
 * 3. Creates Jira sub-tickets for each question
 * 4. Adds "ai_questions_asked" label to parent ticket
 * 5. Assigns parent ticket back to initiator for review
 */

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Parse AI response containing JSON array of questions
 * @param {string} response - Raw AI response
 * @returns {Array} Array of question objects
 */
function parseQuestionsResponse(response) {
    console.log('=== Parsing AI Response ===');
    console.log('Raw response length:', response.length);
    
    // Try to find JSON array in the response
    let jsonMatch = response.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
        console.log('No JSON array found in response');
        return [];
    }
    
    let jsonString = jsonMatch[0];
    console.log('Extracted JSON string:', jsonString);
    
    try {
        let questions = JSON.parse(jsonString);
        console.log('Parsed', questions.length, 'question(s)');
        return questions;
    } catch (error) {
        console.error('Failed to parse JSON:', error);
        console.error('JSON string was:', jsonString);
        return [];
    }
}

/**
 * Build ticket summary (truncate if needed)
 * @param {string} summary - Question summary
 * @param {number} index - Question index (for numbering)
 * @returns {string} Formatted summary
 */
function buildSummary(summary, index) {
    let prefix = '[Q' + (index + 1) + '] ';
    let maxLength = 120; // Jira summary field limit
    let availableLength = maxLength - prefix.length;
    
    if (summary.length > availableLength) {
        summary = summary.substring(0, availableLength - 3) + '...';
    }
    
    return prefix + summary;
}

/**
 * Build ticket description in Jira markdown format
 * @param {object} question - Question object {summary, priority, description}
 * @returns {string} Formatted description
 */
function buildDescription(question) {
    let desc = '';
    
    // Add description if provided
    if (question.description) {
        desc += question.description + '\n\n';
    }
    
    // Add metadata
    desc += '---\n';
    desc += '*Generated by AI Teammate*\n';
    desc += '*Priority: ' + (question.priority || 'Medium') + '*\n';
    
    return desc;
}

/**
 * Extract ticket key from dmtools response
 * @param {string} result - dmtools command result
 * @returns {string|null} Ticket key or null
 */
function extractTicketKey(result) {
    try {
        // dmtools might return JSON or plain text with ticket key
        if (result.includes('{')) {
            let json = JSON.parse(result);
            return json.key || null;
        }
        // Look for pattern like "ATL-123"
        let match = result.match(/[A-Z]+-\d+/);
        return match ? match[0] : null;
    } catch (error) {
        console.error('Failed to extract ticket key:', error);
        return null;
    }
}

// ============================================================================
// MAIN ACTION LOGIC
// ============================================================================

/**
 * Main action function called by dmtools
 * @param {object} params - Parameters from agent configuration
 * @param {object} params.ticket - Parent Jira ticket object
 * @param {string} params.response - AI-generated response
 * @param {string} params.initiator - Jira user ID who initiated the process
 */
function action(params) {
    console.log('\n========================================');
    console.log('LEARNING AI TEAMMATE - QUESTION CREATION');
    console.log('========================================\n');
    
    try {
        // Extract parameters
        const ticketKey = params.ticket.key;
        const initiatorId = params.initiator;
        const aiResponse = params.response;
        
        console.log('Parent ticket:', ticketKey);
        console.log('Initiator:', initiatorId);
        console.log('AI response length:', aiResponse ? aiResponse.length : 0);
        
        // Step 1: Parse questions from AI response
        console.log('\n--- Step 1: Parse Questions ---');
        const questions = parseQuestionsResponse(aiResponse);
        
        if (questions.length === 0) {
            console.log('✅ No questions generated - requirements are clear!');
            console.log('Adding label and completing process...');
            
            // Still add label to indicate AI processed this ticket
            jira_add_label({
                key: ticketKey,
                label: 'ai_no_questions_needed'
            });
            
            return {
                success: true,
                message: 'No clarifying questions needed - requirements are clear',
                questionsCreated: 0
            };
        }
        
        // Step 2: Create sub-tickets for each question
        console.log('\n--- Step 2: Create Sub-tickets ---');
        const projectKey = ticketKey.split('-')[0]; // Extract "ATL" from "ATL-2"
        const createdTickets = [];
        
        questions.forEach(function(question, index) {
            console.log('\nCreating question ' + (index + 1) + ' of ' + questions.length);
            console.log('  Summary:', question.summary);
            console.log('  Priority:', question.priority || 'Medium');
            
            const summary = buildSummary(question.summary, index);
            const description = buildDescription(question);
            
            try {
                // Build fields for Jira ticket creation
                const fieldsJson = {
                    summary: summary,
                    description: description,
                    issuetype: { name: 'Sub-task' }, // Note: Jira uses "Sub-task"
                    parent: { key: ticketKey }
                };
                
                // Add priority if specified
                if (question.priority) {
                    fieldsJson.priority = { name: question.priority };
                }
                
                console.log('  Creating sub-ticket with fields:', JSON.stringify(fieldsJson, null, 2));
                
                // Call dmtools to create the ticket
                const result = jira_create_ticket_with_json({
                    project: projectKey,
                    fieldsJson: fieldsJson
                });
                
                // Extract created ticket key
                const createdKey = extractTicketKey(result);
                
                if (createdKey) {
                    console.log('  ✅ Created:', createdKey);
                    createdTickets.push({
                        key: createdKey,
                        summary: summary,
                        priority: question.priority || 'Medium'
                    });
                } else {
                    console.log('  ⚠️ Ticket created but key not found in response');
                    createdTickets.push({
                        summary: summary,
                        priority: question.priority || 'Medium',
                        key: 'unknown'
                    });
                }
                
            } catch (error) {
                console.error('  ❌ Failed to create sub-ticket:', error);
                createdTickets.push({
                    summary: summary,
                    priority: question.priority || 'Medium',
                    error: error.toString()
                });
            }
        });
        
        // Step 3: Add label to parent ticket
        console.log('\n--- Step 3: Add Label ---');
        try {
            jira_add_label({
                key: ticketKey,
                label: 'ai_questions_asked'
            });
            console.log('✅ Added label "ai_questions_asked" to', ticketKey);
        } catch (error) {
            console.error('❌ Failed to add label:', error);
        }
        
        // Step 4: Assign ticket back to initiator for review
        console.log('\n--- Step 4: Assign for Review ---');
        try {
            jira_assign_ticket({
                key: ticketKey,
                accountId: initiatorId
            });
            console.log('✅ Assigned', ticketKey, 'to', initiatorId, 'for review');
        } catch (error) {
            console.error('❌ Failed to assign ticket:', error);
        }
        
        // Step 5: Return summary
        console.log('\n========================================');
        console.log('PROCESS COMPLETE');
        console.log('========================================');
        console.log('Parent ticket:', ticketKey);
        console.log('Questions created:', createdTickets.length);
        console.log('Successful:', createdTickets.filter(t => !t.error).length);
        console.log('Failed:', createdTickets.filter(t => t.error).length);
        console.log('========================================\n');
        
        return {
            success: true,
            message: 'Created ' + createdTickets.length + ' question sub-tickets for ' + ticketKey,
            parentTicket: ticketKey,
            questionsCreated: createdTickets.length,
            questions: createdTickets
        };
        
    } catch (error) {
        console.error('\n❌ FATAL ERROR ❌');
        console.error(error);
        console.error('Stack trace:', error.stack);
        
        return {
            success: false,
            error: error.toString(),
            stack: error.stack
        };
    }
}

// Export the action function for dmtools to call
// (In Node.js context, this would be module.exports = action)

