# Create sub-tickets for questions
$responseText = Get-Content "outputs/response.md" -Raw
$questions = $responseText | ConvertFrom-Json
$createdTickets = @()
$counter = 1

foreach ($question in $questions) {
    $summary = "[Q${counter}] $($question.summary)"
    if ($summary.Length -gt 120) {
        $summary = $summary.Substring(0, 117) + "..."
    }
    $description = $question.description + "`n`n---`n*Generated by AI Teammate*`n*Priority: $($question.priority)*"
    
    Write-Host "`nCreating Q${counter}..." -ForegroundColor Yellow
    Write-Host "  Summary: $summary" -ForegroundColor White
    
    $parentInput = @{
        project = "ATL"
        issueType = "Sub-task"
        summary = $summary
        description = $description
        parentKey = "ATL-2"
    } | ConvertTo-Json -Depth 5 -Compress
    
    $parentInput | Out-File "temp-parent-$counter.json" -Encoding UTF8 -NoNewline
    $result = Get-Content "temp-parent-$counter.json" -Raw | dmtools jira_create_ticket_with_parent 2>&1
    Remove-Item "temp-parent-$counter.json" -ErrorAction SilentlyContinue
    
    $resultJson = $result | Select-String -Pattern '^{\s*' | Select-Object -First 1
    if ($resultJson) {
        $resultIndex = [array]::IndexOf($result, $resultJson.Line)
        $resultContent = ($result[$resultIndex..($result.Count-1)]) -join "`n" | ConvertFrom-Json
        if ($resultContent.key) {
            Write-Host "  ✅ Created: $($resultContent.key)" -ForegroundColor Green
            $createdTickets += $resultContent.key
        }
    }
    $counter++
}

Write-Host "`n=== Summary ===" -ForegroundColor Cyan
Write-Host "Created $($createdTickets.Count) sub-ticket(s)" -ForegroundColor White
$createdTickets | ForEach-Object { Write-Host "  - $_" -ForegroundColor Green }
